site_name: Simple API Key Rotator
site_description: Rotate API keys to bypass API rate limits
repo_url: https://github.com/evgeniyarbatov/simple-api-key-rotator

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top

nav:
  - Home: index.md
